version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
  tests:
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  database: