version: "3"

networks:
  restaurant_test_network:
    driver: bridge

services:
  test-db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=test_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - restaurant_test_network

  test-app:
    container_name: "test-app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest -v
    ports:
      - "8001:8000"
    depends_on:
      - test-db
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - restaurant_test_network